<script>
  import { base } from '$app/paths';
</script>

<svelte:head>
  <title>Transnational Stages</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
</svelte:head>


<section class="intro-hero">
  <img  class="intro-video" src={base + '/images/homepage-map-image.png'} alt="Map of Atlantic">

  <div class="overlay"></div>

  <div class="hero-text">
    <h1>Transnational Stages</h1>
    <h3 class="subtitle">Theatrical Circulation and Exchange in the Atlantic World, 1680–1850</h3>
    <p class="intro">
      From the seventeenth to the twentieth centuries in the Atlantic World plays and performers often crossed
      land boundaries and oceans, creating new meanings and audience expectations as they did so.
      <strong>Transnational Stages</strong> offers users the opportunity to study national datasets via
      comparative visualization tools, thereby creating new insights into international theatrical trends
      in the Early Modern and Modern periods.
  </p>
  </div>

</section>

<p class="caption">Image generated by ChatGPT</p>


<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family: 'Inter', sans-serif;
    color: #000;
  }

  .subtitle {
    font-style: italic;
  }

  .intro-hero {
    position: relative;
    height: 100vh;
    width: 100%;
    overflow: hidden;
    display: flex;
    align-items: center;
    gap: 2rem;
    padding: 2rem;
  }

  .intro-video {
    flex: 1;
    max-width: 50%;
    /* aspect-ratio: 1/1; */
    width: 100%;
    object-position: right center;
    height: auto;
    object-fit: cover;
    display: block;
    box-shadow: 0px 40px 60px -20px rgba(0, 0, 0, 0.4);
  }


  .hero-text {
    flex: 1;
    text-align: left;
    z-index: 2;
    max-width: 40%;
    padding: 0 1rem;
  }

  .hero-text h1 {
    font-family: 'Inter', sans-serif;
    font-size: 3rem;
    font-weight: 700;
    margin-bottom: 1rem;
  }

  .caption {
    font-size: 0.9rem;
    color: #555;
    margin: 1.5rem;

  }

  .caption a {
    text-decoration: none;
    color: rgb(3, 29, 160);
  }

  .caption a:hover {
    color: rgb(159, 17, 17);
  }

  .intro {
    font-size: 1.05rem;
    line-height: 1.7;
    margin-bottom: 2rem;
  }

  a {
    color: #684c39;
  }

  a:hover {
    text-decoration: underline;
  }

  @media (max-width: 786px){
    .intro-hero{
      flex-direction: column;
      height: auto;
      min-height: 100vh;
      /* padding: 1rem; */
      padding: 7rem 0rem;
    }

    .intro-video{
      max-width: 80%;
      width: 100%;
    }

    .hero-text{
      max-width: 80%;
      text-align: center;
      padding: 1rem 0;
    }
  }
</style>
